import type { EditorThemeClasses } from 'lexical'
import styles from './styles/editor.module.css'

export const editorTheme: EditorThemeClasses = {
  code: styles.codeBlock,
  codeHighlight: {
    atrule: styles.tokenAttr,
    attr: styles.tokenAttr,
    boolean: styles.tokenProperty,
    builtin: styles.tokenSelector,
    cdata: styles.tokenComment,
    char: styles.tokenSelector,
    class: styles.tokenFunction,
    'class-name': styles.tokenFunction,
    comment: styles.tokenComment,
    constant: styles.tokenProperty,
    deleted: styles.tokenDeleted,
    doctype: styles.tokenComment,
    entity: styles.tokenOperator,
    function: styles.tokenFunction,
    important: styles.tokenVariable,
    inserted: styles.tokenInserted,
    keyword: styles.tokenAttr,
    namespace: styles.tokenVariable,
    number: styles.tokenProperty,
    operator: styles.tokenOperator,
    prolog: styles.tokenComment,
    property: styles.tokenProperty,
    punctuation: styles.tokenPunctuation,
    regex: styles.tokenVariable,
    selector: styles.tokenSelector,
    string: styles.tokenSelector,
    symbol: styles.tokenProperty,
    tag: styles.tokenProperty,
    url: styles.tokenOperator,
    variable: styles.tokenVariable,
  },
  heading: {
    h1: styles.heading1,
    h2: styles.heading2,
    h3: styles.heading3,
    h4: styles.heading4,
  },
  hr: styles.hr,
  image: styles.image,
  link: styles.link,
  list: {
    checklist: styles.checkList,
    listitem: styles.listItem,
    listitemChecked: styles.listItemChecked,
    listitemUnchecked: styles.listItemUnchecked,
    nested: {
      listitem: styles.nestedListItem,
    },
    ol: styles.orderedList,
    ul: styles.unorderedList,
  },
  ltr: styles.ltr,
  paragraph: styles.paragraph,
  quote: styles.quote,
  rtl: styles.rtl,
  table: styles.table,
  tableCell: styles.tableCell,
  tableCellHeader: styles.tableCellHeader,
  tableRow: styles.tableRow,
  text: {
    bold: styles.bold,
    code: styles.inlineCode,
    italic: styles.italic,
    strikethrough: styles.strikethrough,
    underline: styles.underline,
  },
}

export { styles as editorStyles }
